# Site settings
title: boring stuff
email: 
description: "Download space for everything in my brain. Opinionated views on AI, software engineering and other boring stuff."
baseurl: ""
url: "https://boringftw.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
