# Site settings
title: Mind Your Agents
email: 
description: Opinionated views on agentic AI and software engineering. 
baseurl: ""
url: "https://mindyouragents.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  software:
    output: true