# Site settings
title: mind your agents!
email: 
description: "On generative AI, agentic AI, unicorn AI 🦄 and all fancy things you've been hearing. Also on good ol' software engineering sometimes!"
baseurl: ""
url: "https://mindyouragents.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
