# Site settings
title: mind your agents!
email: 
description: | 
  On Generative AI, agentic AI 🤖 and software engineering in general. 
baseurl: ""
url: "https://mindyouragents.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
