# Site settings
title: rockpaperAI
email: 
description: "Download space for everything in my brain. Opinionated views on software engineering, AI and other random stuff."
baseurl: ""
url: "https://rockpaperai.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
