# Site settings
title: shut up saurav!
email: 
description: "Download space for everything in my brain. Opinionated views on software engineering, AI, tech, finance and other boring stuff."
baseurl: ""
url: "http://shutupsaurav.github.io"
linkedin_username: sauravdey
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
